Feature : Adding a friend
TravelPouch/travelpouch pull request #217
Opened 2024-11-23 23:54 UTC by yassine04e

feat: Implementing the possibility of adding a friend and changing the type of the varibla friends from Map? to List

2024-11-27 16:01 UTC, Unsaved2 requested changes
Great work, this PR adds a social dimension that we were missing. I just have some concerns.

The first one is when you add a friend. There are no friend requests and the other user is forced to be friends with the person. It might be good in a future PR to use the notificationScreen to make friend requests.

The second concern is that I don't really understand the usefulness of modes in TravelRepositoryFirestore . I think it would be preferable to add different function instead of modes.

Another thing, it would also be nice in a next PR to be able to delete friends

Otherwise adding a friend works and I haven't found any issues, nice work !

2024-11-28 04:01 UTC, yassine04e commented on app/src/main/java/com/github/se/travelpouch/model/profile/ProfileModelView.kt
> +          onSuccess()
Yes, you are right

2024-11-28 04:04 UTC, yassine04e commented on app/src/main/java/com/github/se/travelpouch/model/profile/ProfileRepositoryFirebase.kt
> +      updatingFunction: (Profile, String) -> Profile,
Yes, you are right. This is done

2024-11-28 04:05 UTC, yassine04e commented on app/src/main/java/com/github/se/travelpouch/model/travels/ListTravelViewModel.kt
> +  fun updateTravel(travel: TravelContainer, modeOfUpdate: Int, fsUidOfAddedParticipant: String?) {
I wanted to modify the smallest amount of code possible. Otherwise, I would have added functions, and had to modify other screens logic.

2024-11-28 04:32 UTC, yassine04e commented on app/src/main/java/com/github/se/travelpouch/model/travels/TravelRepositoryFirestore.kt
> +    if (modeOfUpdate == 0) {
Yes, you are right, it is cleaner

2024-11-28 04:33 UTC, yassine04e commented on app/src/main/java/com/github/se/travelpouch/model/travels/TravelRepositoryFirestore.kt
> +    if (modeOfUpdate == 0) {
I sticked with the switch method because it reduces the amount of function to add and the tests to update

2024-11-28 04:34 UTC, yassine04e commented on app/src/main/java/com/github/se/travelpouch/model/profile/ProfileModelView.kt
> +    return profile.copy(friends = friends.toList())
Yes, you are right

2024-11-28 04:34 UTC, yassine04e commented on app/src/main/java/com/github/se/travelpouch/ui/profile/ProfileScreen.kt
> +                                "You have no friend. [insert sad Titanic music]. \n ... \n [insert phonk tik tok music] Stay hard. They don't know you, son",
Yes, it was more for the joke. But yes, I can surely put something more appropriate

2024-11-28 04:37 UTC, yassine04e commented on app/src/main/java/com/github/se/travelpouch/model/profile/ProfileModelView.kt
> +
Yes, you are right

2024-11-28 04:38 UTC, yassine04e commented on app/src/main/java/com/github/se/travelpouch/model/profile/ProfileRepository.kt
> +
Yes, you are right. I added it

2024-11-28 12:29 UTC, Unsaved2 approved these changes
Thank you for considering my suggestions. Adding a friend works as expected and I haven't found any issues so we can merge it !

2024-11-28 14:51 UTC, yassine04e commented
To answer your first comment, I will add the fiollowing features in a following sprint : 
1) Removing a friend
2) Sending notification to add a friend

2024-11-28 14:51 UTC, merged