UI and UX improvements
TravelPouch/travelpouch pull request #265
Opened 2024-12-15 22:58 UTC by RemIsMyWaifuu

Copied from #264:

Description:
There is a range of diverse UI/UX improvements to enhance the overall user experience and ensure a consistency that are needed. For instance, notifications screen doesn't update correctly and the calendar screen has dark/light theme issues.
Acceptance Criteria:
- Notifications screen should update its View if a notification was accepted and the update to firestore is successful.
- Calendar needs to conform to dark/light theme.

2024-12-15 22:59 UTC, RemIsMyWaifuu commented
Closes #264

2024-12-17 03:22 UTC, yassine04e reviewed
Nothing more to add. Good improvements. Just remove some of the ocde you left commented and we are good to go

2024-12-17 03:22 UTC, yassine04e commented on app/src/main/java/com/github/se/travelpouch/ui/notifications/NotificationsScreen.kt
> +                          notificationViewModel.loadNotificationsForUser(profile.value.fsUid)
Good call, since it does not refresh the notifications on this screen

2024-12-17 03:22 UTC, yassine04e commented on app/src/main/java/com/github/se/travelpouch/ui/dashboard/CalendarViewComposable.kt
> +                modifier = Modifier.weight(1f, fill = false))
Good use of fill to center the days

2024-12-17 03:25 UTC, yassine04e requested changes
I have noticed one thing in your code. When signing up or log in with email and password, there is no circular animation. I think you must add it, since it will homogenise the sign in page. 
Also, when logging in with google (so in SignInScreen), if I spam the button to log in with email and password, I will first go to the page to sign in with email and password, then jump on the screen with the list of travels. 
So, I think you need to keep the boolean of methodChosen to true even when loggin successful. 
Similarly, I did not check this in SignInWithPassword function, but I think we have the same problem.

Also, there is a major problem in Notification Screen. When spamming the two buttons , ACCEPT and DECLINE, there is multiple contradictory toasts displayed, which is a problem. Also, after an experiment, I joined a travel but the notification sent was that I DECLINED the invitation. So, to correct it, I would recommand to have a boolean, similar to the ones in SignInWithPassword screen, that blocks the buttons until the notification disappears or if the sending of the answer failed.

2024-12-17 17:16 UTC, RemIsMyWaifuu commented
> I have noticed one thing in your code. When signing up or log in with email and password, there is no circular animation. I think you must add it, since it will homogenise the sign in page. 

Yes, but the email login was added after the spinner was originally inserted. The spinner should have been baked in at inception of the alternative login form not after the fact. Furthermore, this would massively blow up the scope of this PR and line amount as well as testing amount for which we do not have time. This should have been addressed 4 sprints ago...

> Also, when logging in with google (so in SignInScreen), if I spam the button to log in with email and password, I will first go to the page to sign in with email and password, then jump on the screen with the list of travels. So, I think you need to keep the boolean of methodChosen to true even when loggin successful. Similarly, I did not check this in SignInWithPassword function, but I think we have the same problem.

Unfortunately, what you're proposing doesn't solve the issue. Even if methodChosen is set to false AFTER the call to navigationActions.navigateTo(Screen.TRAVEL_LIST) this still leaves a small opportunity for spamming due to the async nature of the navigation. This again is a strange, undefined behaviour case.

> Also, there is a major problem in Notification Screen. When spamming the two buttons , ACCEPT and DECLINE, there is multiple contradictory toasts displayed, which is a problem. Also, after an experiment, I joined a travel but the notification sent was that I DECLINED the invitation. So, to correct it, I would recommand to have a boolean, similar to the ones in SignInWithPassword screen, that blocks the buttons until the notification disappears or if the sending of the answer failed.

Again, just as for the previous case it's a very hard to address "bug" for a small to no benefit. At some point we can't protect the user against the strangeness of jetpack compose and async functions.

2024-12-17 18:51 UTC, yassine04e commented
> Unfortunately, what you're proposing doesn't solve the issue. Even if methodChosen is set to false AFTER the call to navigationActions.navigateTo(Screen.TRAVEL_LIST) this still leaves a small opportunity for spamming due to the async nature of the navigation. This again is a strange, undefined behaviour case.
> No, what I suggest would be to keep the method chosen to true.

2024-12-18 23:40 UTC, yassine04e commented
To help you I have added the small fixes I talked about. Concerning the spinner in email and password screen, I agree that it should have been added before. However, this screen was mostly added for the first e2e test success. I assume that it was not supposed to be a final product screen. For this reason, I will not count it as the goal of this PR. But I will still try to do something about it in another PR. Apart from that. the PR is complete so we can merge it.

2024-12-18 23:41 UTC, yassine04e approved these changes
This PR can be merged, as no bug was noticed

2024-12-19 09:41 UTC, merged